In [1]:
People = {
    "first" : ['ujas','mahek','jigar'],
    "last" : ['lathiya','khanapara','vavaliya'],
    "email" : ['ujas123@gmail.com','mahek234@gmail.com','jigar@gmail.com']
}

In [2]:
import pandas as pd
df = pd.DataFrame(People)
df

   first       last               email
0   ujas    lathiya   ujas123@gmail.com
1  mahek  khanapara  mahek234@gmail.com
2  jigar   vavaliya     jigar@gmail.com

In [3]:
df.set_index('first')

            last               email
first
ujas     lathiya   ujas123@gmail.com
mahek  khanapara  mahek234@gmail.com
jigar   vavaliya     jigar@gmail.com

In [4]:
df

   first       last               email
0   ujas    lathiya   ujas123@gmail.com
1  mahek  khanapara  mahek234@gmail.com
2  jigar   vavaliya     jigar@gmail.com

In [5]:
df.set_index('first', inplace=True)

In [6]:
df

            last               email
first
ujas     lathiya   ujas123@gmail.com
mahek  khanapara  mahek234@gmail.com
jigar   vavaliya     jigar@gmail.com

In [7]:
df.reset_index()

   first       last               email
0   ujas    lathiya   ujas123@gmail.com
1  mahek  khanapara  mahek234@gmail.com
2  jigar   vavaliya     jigar@gmail.com

In [8]:
df.reset_index(inplace=True)

In [9]:
df

   first       last               email
0   ujas    lathiya   ujas123@gmail.com
1  mahek  khanapara  mahek234@gmail.com
2  jigar   vavaliya     jigar@gmail.com

In [10]:
public_df = pd.read_csv('survey_results_public.csv', index_col='ResponseId')
public_df

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,5,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,2,...,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,...,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0

In [11]:
public_df.sort_index(ascending=False)

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,...,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0
83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,2,...,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,5,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0

In [12]:
public_df.set_index('Country',inplace=True)

In [13]:
public_df.sort_index()

,MainBranch,Employment,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,I am a student who is learning to code,"Student, part-time",NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Younger than 5 years,Books / Physical media,NaN,NaN,NaN,...,Under 18 years old,"Or, in your own words:","Or, in your own words:",Straight / Heterosexual;Bisexual;Prefer to sel...,White or of European descent;I don't know;Mult...,"Or, in your own words:","Or, in your own words:",Too long,Difficult,NaN
Afghanistan,I am a developer by profession,"Not employed, but looking for work",NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,"Developer, mobile;Developer, front-end;Develop...",...,18-24 years old,Man,No,Straight / Heterosexual,Middle Eastern,None of the above,None of the above,Appropriate in length,Easy,NaN
Afghanistan,I am a developer by profession,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,"I am not primarily a developer, but I write co...","Not employed, but looking for work",NaN,NaN,Some college/university study without earning ...,18 - 24 years,Books / Physical media,6,NaN,"Developer, desktop or enterprise applications",...,25-34 years old,Man,No,Straight / Heterosexual,Multiracial;Indigenous (such as Native America...,None of the above,None of the above,Too long,Difficult,NaN
Afghanistan,I am a developer by profession,Employed full-time,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,8,4,"Developer, front-end;Developer, full-stack;Dev...",...,25-34 years old,Man,No,NaN,South Asian,None of the above,None of the above,Appropriate in length,Easy,4200.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zimbabwe,I am a developer by profession,Employed full-time,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",18,14,"Developer, back-end;Database administrator;Sys...",...,35-44 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Too long,Easy,NaN
Zimbabwe,I code primarily as a hobby,"Not employed, and not looking for work",NaN,NaN,Primary/elementary school,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",Less than 1 year,NaN,NaN,...,Under 18 years old,Man,No,Straight / Heterosexual,Black or of African descent,I am blind / have difficulty seeing,None of the above,Appropriate in length,Easy,NaN
Zimbabwe,I am a developer by profession,"Student, part-time",NaN,NaN,Some college/university study without earning ...,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",5,NaN,NaN,...,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
Zimbabwe,I am a developer by profession,Employed full-time,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",5,1,"Developer, full-stack",...,25-34 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,2400.0
Zimbabwe,I am a developer by profession,Employed full-time,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",5 - 10 years,Coding Bootcamp;Other online resources (ex: vi...,10,6,"Developer, mobile;Developer, front-end;Develop...",...,25-34 years old,Woman,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN

In [14]:
public_df.sort_index(inplace=True)

In [15]:
public_df['Employment']

Country
Afghanistan                        Student, part-time
Afghanistan        Not employed, but looking for work
Afghanistan                                       NaN
Afghanistan        Not employed, but looking for work
Afghanistan                        Employed full-time
                                ...
Zimbabwe                           Employed full-time
Zimbabwe       Not employed, and not looking for work
Zimbabwe                           Student, part-time
Zimbabwe                           Employed full-time
Zimbabwe                           Employed full-time
Name: Employment, Length: 83439, dtype: object